# Generated by Django 5.2.7 on 2025-10-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttachmentType",
            fields=[
                (
                    "attachment_type_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("type_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "attachment_types",
            },
        ),
        migrations.CreateModel(
            name="CaseStatus",
            fields=[
                (
                    "case_status_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("case_status_name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "case_statuses",
            },
        ),
        migrations.CreateModel(
            name="CaseType",
            fields=[
                (
                    "case_type_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("case_type_name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "case_types",
            },
        ),
        migrations.CreateModel(
            name="DocumentStatus",
            fields=[
                ("status_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status_name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "document_statuses",
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "document_type_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("type_name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "document_types",
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                ("field_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("field_name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "fields",
            },
        ),
        migrations.CreateModel(
            name="IssueLevel",
            fields=[
                (
                    "issue_level_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("level_name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "issue_levels",
            },
        ),
        migrations.CreateModel(
            name="SecurityLevel",
            fields=[
                (
                    "security_level_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("level_name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "security_levels",
            },
        ),
        migrations.CreateModel(
            name="UrgencyLevel",
            fields=[
                (
                    "urgency_level_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("level_name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "urgency_levels",
            },
        ),
    ]
