# Generated by Django 5.2.7 on 2025-10-29 20:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                ("report_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("config_json", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_definitions",
            },
        ),
        migrations.CreateModel(
            name="ReportExport",
            fields=[
                ("export_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "exported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("XLSX", "XLSX"), ("CSV", "CSV")],
                        max_length=10,
                    ),
                ),
                ("params_json", models.JSONField(blank=True, null=True)),
                ("file_path", models.CharField(max_length=500)),
                (
                    "exported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="reports.reportdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "report_exports",
            },
        ),
    ]
