# Generated by Django 5.2.7 on 2025-10-29 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("REMINDER", "REMINDER"),
                            ("REPORT_EXPORT", "REPORT_EXPORT"),
                            ("SYNC_MAIL", "SYNC_MAIL"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload_json", models.JSONField()),
                ("run_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "QUEUED"),
                            ("RUNNING", "RUNNING"),
                            ("DONE", "DONE"),
                            ("FAILED", "FAILED"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "db_table": "jobs",
                "indexes": [
                    models.Index(
                        fields=["run_at", "status"], name="jobs_run_at_5fa60c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.CharField(blank=True, max_length=1000, null=True)),
                ("link", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("app", "app"), ("email", "email"), ("sms", "sms")],
                        default="app",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "indexes": [
                    models.Index(
                        fields=["user", "read_at"],
                        name="notificatio_user_id_6c7360_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("reminder_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("document", "document"),
                            ("case", "case"),
                            ("task", "task"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                ("due_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SENT", "SENT"),
                            ("CLEARED", "CLEARED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reminders",
                "indexes": [
                    models.Index(
                        fields=["due_at", "status"], name="reminders_due_at_c9ed42_idx"
                    )
                ],
            },
        ),
    ]
