# Generated by Django 5.2.7 on 2025-11-29 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                ("rule_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(help_text="Tên quy tắc tự động", max_length=200),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("assignment", "Khi phân công"),
                            ("status_change", "Khi đổi trạng thái"),
                            ("deadline", "Gần hạn deadline"),
                        ],
                        help_text="Sự kiện kích hoạt",
                        max_length=50,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Quy tắc có đang hoạt động không"
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list,
                        help_text="Danh sách kênh gửi thông báo: ['email', 'push', 'sms']",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text="Điều kiện kích hoạt (vd: hours_before, priority, etc.)",
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        blank=True, default="", help_text="Mẫu nội dung thông báo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "automation_rules",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["trigger", "is_enabled"],
                        name="automation__trigger_7d3bb6_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                ("channel_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("sms", "SMS"),
                        ],
                        help_text="Type of notification channel",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether this channel is active"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Channel configuration (SMTP settings, API keys, etc.) - plain JSON for demo",
                    ),
                ),
                (
                    "sent_count",
                    models.IntegerField(
                        default=0, help_text="Total notifications sent via this channel"
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        default=0, help_text="Total failed notifications"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this channel was used",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_channels",
                "indexes": [
                    models.Index(
                        fields=["channel_type"], name="notificatio_channel_02fbcc_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "channel",
                    models.CharField(
                        help_text="Kênh gửi: email, push, sms", max_length=20
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Người nhận (email hoặc user_id)", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Tiêu đề thông báo", max_length=500),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, default="", help_text="Nội dung thông báo"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Đã gửi"),
                            ("failed", "Thất bại"),
                            ("pending", "Đang chờ"),
                        ],
                        default="pending",
                        help_text="Trạng thái gửi",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, help_text="Thời gian gửi"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Thông báo lỗi nếu gửi thất bại",
                        null=True,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quy tắc tự động kích hoạt (nếu có)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.automationrule",
                    ),
                ),
            ],
            options={
                "db_table": "notification_logs",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "status"],
                        name="notificatio_channel_d7ad6a_idx",
                    ),
                    models.Index(
                        fields=["sent_at"], name="notificatio_sent_at_85d1ed_idx"
                    ),
                ],
            },
        ),
    ]
