from pathlib import Path
import re
path = Path('templates/chuyenvien/vanbandi-detail.html')
text = path.read_text(encoding='utf-8')
pattern = re.compile(r'<aside class="card doc-card" id="doc-workflow-panel">.*?</aside>', re.S)
if not pattern.search(text):
    raise SystemExit('pattern not found')
new = """              <aside\n                class=\"card doc-card\"\n                id=\"doc-workflow-panel\"\n                data-direction=\"OUTBOUND\"\n                data-role=\"CV\"\n                data-route=\"vanbandi\"\n                data-allow-withdraw=\"1\"\n              >\n                <header>\n                  <h2 class=\"text-[15px] font-semibold text-slate-800\">Lu?ng x? l? Vãn thý</h2>\n                  <p class=\"text-[12.5px] text-slate-500\">DRAFT ? SUBMITTED ? LD ? VT ? QT ? ARCHIVE</p>\n                </header>\n                <ol data-wf=\"steps\" class=\"space-y-2 text-[13px] text-slate-500\">\n                  <li>Ðang t?i tr?ng thái workflow…</li>\n                </ol>\n                <div class=\"space-y-2\">\n                  <label class=\"text-[13px] font-medium text-slate-700\" for=\"cv-workflow-action\">Hành ð?ng ðý?c phép</label>\n                  <select data-wf=\"action-select\" id=\"cv-workflow-action\" class=\"w-full h-10 rounded-md border border-slate-200 px-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-600/20 focus:border-blue-500 disabled:bg-slate-50\"></select>\n                </div>\n                <div data-wf=\"fields\" class=\"space-y-3 hidden\"></div>\n                <div class=\"flex flex-wrap items-center gap-2\">\n                  <button type=\"button\" data-wf=\"submit\" class=\"h-9 rounded-md bg-blue-600 px-3 text-sm font-medium text-white hover:bg-blue-700 shadow-sm disabled:opacity-60 disabled:cursor-not-allowed\">Th?c hi?n</button>\n                  <button type=\"button\" data-wf=\"withdraw\" class=\"h-9 rounded-md border border-slate-200 px-3 text-sm font-medium text-rose-600 hover:bg-rose-50\">Thu h?i</button>\n                </div>\n                <p data-wf=\"message\" class=\"text-[12.5px] text-slate-500\"></p>\n              </aside>"""
text = pattern.sub(new, text, count=1)
path.write_text(text, encoding='utf-8')
