# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='include_user_docs',
            field=models.BooleanField(default=True, help_text="If True, chatbot can search user's documents"),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_context',
            field=models.JSONField(blank=True, help_text='Snapshot of user info: {username, full_name, role, department_name, department_code}', null=True),
        ),
    ]
