# Generated by Django 5.2.7 on 2025-10-29 20:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "organization_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("tax_code", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("document_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "doc_direction",
                    models.CharField(
                        choices=[("den", "den"), ("di", "di"), ("du_thao", "du_thao")],
                        max_length=20,
                    ),
                ),
                (
                    "document_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "issue_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("title", models.CharField(max_length=500)),
                ("is_legal_doc", models.BooleanField(default=False)),
                (
                    "signing_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "signer_position",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("received_number", models.IntegerField(blank=True, null=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                ("sender", models.CharField(blank=True, max_length=250, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.department",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.documenttype",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.field",
                    ),
                ),
                (
                    "issue_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.issuelevel",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "security_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.securitylevel",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.documentstatus",
                    ),
                ),
                (
                    "urgency_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.urgencylevel",
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="DocumentApproval",
            fields=[
                ("approval_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("step_no", models.IntegerField()),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APPROVE", "APPROVE"),
                            ("REJECT", "REJECT"),
                            ("PENDING", "PENDING"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("sign_hash", models.CharField(blank=True, max_length=200, null=True)),
                ("sign_meta", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_approvals",
            },
        ),
        migrations.CreateModel(
            name="DocumentAssignment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role_on_doc",
                    models.CharField(
                        choices=[
                            ("owner", "owner"),
                            ("assignee", "assignee"),
                            ("watcher", "watcher"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("is_owner", models.BooleanField(default=False)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doc_assigned_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_assignments",
            },
        ),
        migrations.CreateModel(
            name="DocumentAttachment",
            fields=[
                (
                    "attachment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attachment_type", models.CharField(max_length=20)),
                ("file_name", models.CharField(max_length=200)),
                ("storage_path", models.CharField(max_length=500)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_attachments",
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("version_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version_no", models.IntegerField()),
                ("file_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "storage_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_versions",
            },
        ),
        migrations.CreateModel(
            name="DocumentWorkflowLog",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "RECEIVED"),
                            ("ASSIGNED", "ASSIGNED"),
                            ("SUBMITTED", "SUBMITTED"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                            ("SIGNED", "SIGNED"),
                            ("PUBLISHED", "PUBLISHED"),
                        ],
                        max_length=50,
                    ),
                ),
                ("acted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("comment", models.CharField(blank=True, max_length=500, null=True)),
                ("meta_json", models.JSONField(blank=True, null=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_logs",
                        to="documents.document",
                    ),
                ),
                (
                    "from_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_from",
                        to="catalog.documentstatus",
                    ),
                ),
                (
                    "to_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_to",
                        to="catalog.documentstatus",
                    ),
                ),
            ],
            options={
                "db_table": "document_workflow_logs",
            },
        ),
        migrations.CreateModel(
            name="OrgContact",
            fields=[
                ("contact_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="documents.organization",
                    ),
                ),
            ],
            options={
                "db_table": "org_contacts",
            },
        ),
        migrations.CreateModel(
            name="DispatchOutbox",
            fields=[
                ("dispatch_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("buu_chinh", "bưu chính"),
                            ("email", "email"),
                            ("cong_dvc", "cổng DVC"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SENT", "SENT"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "tracking_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("note", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="documents.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.organization",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.orgcontact",
                    ),
                ),
            ],
            options={
                "db_table": "dispatch_outbox",
            },
        ),
        migrations.CreateModel(
            name="OutgoingNumbering",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("seq", models.IntegerField()),
                ("prefix", models.CharField(blank=True, max_length=20, null=True)),
                ("postfix", models.CharField(blank=True, max_length=20, null=True)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "outgoing_numbering",
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["doc_direction", "status"], name="documents_doc_dir_7c9993_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["department"], name="documents_departm_ec72b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["issued_date"], name="documents_issued__311f69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="documents_created_3c6eaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "title", "sender", config="simple"
                ),
                name="doc_title_sender_fts",
            ),
        ),
        # migrations.AddConstraint(
        #     model_name="document",
        #     constraint=models.CheckConstraint(
        #         condition=models.Q(
        #             models.Q(
        #                 ("doc_direction", "di"),
        #                 ("issue_number__isnull", False),
        #                 ("issued_date__isnull", False),
        #             ),
        #             models.Q(("doc_direction", "di"), _negated=True),
        #             _connector="OR",
        #         ),
        #         name="chk_doc_di_require_issue",
        #     ),
        # ),
        # migrations.AddConstraint(
        #     model_name="document",
        #     constraint=models.CheckConstraint(
        #         condition=models.Q(
        #             models.Q(
        #                 ("doc_direction", "den"),
        #                 ("received_date__isnull", False),
        #                 ("received_number__isnull", False),
        #                 ("sender__isnull", False),
        #             ),
        #             models.Q(("doc_direction", "den"), _negated=True),
        #             _connector="OR",
        #         ),
        #         name="chk_doc_den_require_recv",
        #     ),
        # ),
        # migrations.AddConstraint(
        #     model_name="document",
        #     constraint=models.CheckConstraint(
        #         condition=models.Q(
        #             models.Q(
        #                 ("doc_direction", "du_thao"), ("document_code__isnull", False)
        #             ),
        #             models.Q(("doc_direction", "du_thao"), _negated=True),
        #             _connector="OR",
        #         ),
        #         name="chk_doc_duthao_require_code",
        #     ),
        # ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(
                name='chk_doc_di_require_issue',
                check=Q(doc_direction='di', issue_number__isnull=False, issued_date__isnull=False) | ~Q(doc_direction='di'),
            ),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(
                name='chk_doc_den_require_recv',
                check=Q(doc_direction='den', received_number__isnull=False, received_date__isnull=False, sender__isnull=False) | ~Q(doc_direction='den'),
            ),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(
                name='chk_doc_duthao_require_code',
                check=Q(doc_direction='du_thao', document_code__isnull=False) | ~Q(doc_direction='du_thao'),
            ),
        ),

        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("doc_direction", "di")),
                fields=("issue_number",),
                name="uq_issue_number_di_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentapproval",
            constraint=models.UniqueConstraint(
                fields=("document", "step_no"), name="uq_document_step"
            ),
        ),
        migrations.AddIndex(
            model_name="documentassignment",
            index=models.Index(fields=["user"], name="document_as_user_id_4564b5_idx"),
        ),
        migrations.AddIndex(
            model_name="documentassignment",
            index=models.Index(fields=["due_at"], name="document_as_due_at_60d3a4_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentassignment",
            constraint=models.UniqueConstraint(
                fields=("document", "user"), name="uq_document_user"
            ),
        ),
        migrations.AddIndex(
            model_name="documentattachment",
            index=models.Index(
                fields=["document", "uploaded_at"],
                name="document_at_documen_2361a6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "version_no"), name="uq_document_version_no"
            ),
        ),
        migrations.AddIndex(
            model_name="documentworkflowlog",
            index=models.Index(
                fields=["document", "acted_at"], name="document_wo_documen_cf4bdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orgcontact",
            index=models.Index(
                fields=["organization"], name="org_contact_organiz_f0b23c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchoutbox",
            index=models.Index(
                fields=["document", "status"], name="dispatch_ou_documen_e4242f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchoutbox",
            index=models.Index(
                fields=["sent_at"], name="dispatch_ou_sent_at_6125bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outgoingnumbering",
            index=models.Index(
                fields=["issued_at"], name="outgoing_nu_issued__4da9a1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="outgoingnumbering",
            constraint=models.UniqueConstraint(
                fields=("year", "seq"), name="uq_year_seq"
            ),
        ),
    ]
