# Generated by Django 5.2.7 on 2025-11-06 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('template_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('doc_direction', models.CharField(choices=[('den', 'den'), ('di', 'di'), ('du_thao', 'du_thao')], default='du_thao', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.TextField()),
                ('format', models.CharField(default='html', help_text='Định dạng nội dung (html, docx, ...)', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_templates',
                'indexes': [models.Index(fields=['doc_direction', 'is_active'], name='document_te_doc_dir_434468_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'doc_direction'), name='uq_template_name_direction')],
            },
        ),
        migrations.CreateModel(
            name='NumberingRule',
            fields=[
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('target', models.CharField(choices=[('incoming', 'Văn bản đến'), ('outgoing', 'Văn bản đi')], max_length=20)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('padding', models.PositiveSmallIntegerField(default=4)),
                ('start_sequence', models.PositiveIntegerField(default=1)),
                ('next_sequence', models.PositiveIntegerField(default=1)),
                ('reset_policy', models.CharField(choices=[('yearly', 'Reset mỗi năm'), ('monthly', 'Reset mỗi tháng'), ('manual', 'Tự reset thủ công')], default='yearly', max_length=20)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numbering_rules_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numbering_rules_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'numbering_rules',
                'indexes': [models.Index(fields=['target', 'is_active'], name='numbering_r_target_673b86_idx'), models.Index(fields=['department'], name='numbering_r_departm_c2b138_idx')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='uq_numbering_rule_code')],
            },
        ),
        migrations.CreateModel(
            name='RegisterBook',
            fields=[
                ('register_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('direction', models.CharField(choices=[('den', 'Văn bản đến'), ('di', 'Văn bản đi')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('padding', models.PositiveSmallIntegerField(default=4)),
                ('next_sequence', models.PositiveIntegerField(default=1)),
                ('reset_policy', models.CharField(choices=[('yearly', 'Reset mỗi năm'), ('quarterly', 'Reset mỗi quý'), ('monthly', 'Reset mỗi tháng'), ('never', 'Không tự reset')], default='yearly', max_length=20)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_books_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_books_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'register_books',
                'indexes': [models.Index(fields=['direction', 'year'], name='register_bo_directi_e8839a_idx'), models.Index(fields=['is_active'], name='register_bo_is_acti_a77444_idx')],
                'constraints': [models.UniqueConstraint(fields=('direction', 'year', 'name'), name='uq_register_book_direction_year_name')],
            },
        ),
    ]
