# Generated by Django 5.2.7 on 2025-12-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0009_remove_documentworkflowlog_document_wo_documen_cf4bdb_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentworkflowlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "RECEIVED"),
                    ("ASSIGNED", "ASSIGNED"),
                    ("SUBMITTED", "SUBMITTED"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("SIGNED", "SIGNED"),
                    ("PUBLISHED", "PUBLISHED"),
                    ("VT_CREATE_INBOUND", "VT_CREATE_INBOUND"),
                    ("VT_UPDATE_METADATA", "VT_UPDATE_METADATA"),
                    ("LD_ASSIGN_OFFICER", "LD_ASSIGN_OFFICER"),
                    ("CV_START_PROCESSING", "CV_START_PROCESSING"),
                    ("CV_SUBMIT_FOR_APPROVAL", "CV_SUBMIT_FOR_APPROVAL"),
                    ("LD_APPROVE_INBOUND", "LD_APPROVE_INBOUND"),
                    ("LD_REQUEST_CHANGES_INBOUND", "LD_REQUEST_CHANGES_INBOUND"),
                    ("LD_HANDLE_CLERK_REJECTION", "LD_HANDLE_CLERK_REJECTION"),
                    ("VT_FINAL_CHECK_REJECT_INBOUND", "VT_FINAL_CHECK_REJECT_INBOUND"),
                    ("VT_FINAL_CHECK_OK_INBOUND", "VT_FINAL_CHECK_OK_INBOUND"),
                    ("VT_REGISTER_INBOUND", "VT_REGISTER_INBOUND"),
                    ("VT_DISPATCH_RESULT", "VT_DISPATCH_RESULT"),
                    ("VT_ARCHIVE_INBOUND", "VT_ARCHIVE_INBOUND"),
                    ("CV_REQUEST_REASSIGN", "CV_REQUEST_REASSIGN"),
                    ("QT_RECALL_INBOUND", "QT_RECALL_INBOUND"),
                    ("CV_CREATE_DRAFT", "CV_CREATE_DRAFT"),
                    ("CV_UPDATE_DRAFT", "CV_UPDATE_DRAFT"),
                    ("CV_SUBMIT_DRAFT", "CV_SUBMIT_DRAFT"),
                    ("LD_REQUEST_CHANGES_OUTBOUND", "LD_REQUEST_CHANGES_OUTBOUND"),
                    ("LD_APPROVE_OUTBOUND", "LD_APPROVE_OUTBOUND"),
                    ("LD_REQUEST_CHANGES_FROM_CLERK", "LD_REQUEST_CHANGES_FROM_CLERK"),
                    ("VT_RECEIVE_FOR_FINAL_CHECK", "VT_RECEIVE_FOR_FINAL_CHECK"),
                    ("VT_FINAL_CHECK_OK_OUTBOUND", "VT_FINAL_CHECK_OK_OUTBOUND"),
                    ("VT_REGISTER_OUTBOUND", "VT_REGISTER_OUTBOUND"),
                    (
                        "VT_FINAL_CHECK_REJECT_OUTBOUND",
                        "VT_FINAL_CHECK_REJECT_OUTBOUND",
                    ),
                    ("VT_ISSUE_OUTBOUND", "VT_ISSUE_OUTBOUND"),
                    ("VT_ARCHIVE_OUTBOUND", "VT_ARCHIVE_OUTBOUND"),
                    ("QT_CANCEL_ISSUED_OUTBOUND", "QT_CANCEL_ISSUED_OUTBOUND"),
                    ("QT_FIX_STATE_MANUALLY", "QT_FIX_STATE_MANUALLY"),
                    ("MANUAL_LOG", "MANUAL_LOG"),
                ],
                max_length=50,
            ),
        ),
    ]
