# Generated by Django 5.2.7 on 2025-11-06 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'idempotency_keys',
                'indexes': [models.Index(fields=['key', 'owner', 'path', 'method'], name='idempotency_key_13541e_idx'), models.Index(fields=['expires_at'], name='idempotency_expires_6c9d28_idx')],
                'unique_together': {('key', 'owner', 'path', 'method')},
            },
        ),
    ]
