# Generated by Django 5.2.7 on 2025-10-29 20:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalog", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                ("case_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("case_code", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=250)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("priority", models.CharField(blank=True, max_length=20, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "case_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.casetype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.department",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_leading",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases_owning",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.casestatus",
                    ),
                ),
            ],
            options={
                "db_table": "cases",
            },
        ),
        migrations.CreateModel(
            name="CaseActivityLog",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "CREATE"),
                            ("UPDATE", "UPDATE"),
                            ("CLOSE", "CLOSE"),
                            ("REOPEN", "REOPEN"),
                            ("ASSIGN", "ASSIGN"),
                        ],
                        max_length=50,
                    ),
                ),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.CharField(blank=True, max_length=500, null=True)),
                ("meta_json", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "db_table": "case_activity_logs",
            },
        ),
        migrations.CreateModel(
            name="CaseAttachment",
            fields=[
                (
                    "attachment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attachment_type", models.CharField(max_length=20)),
                ("file_name", models.CharField(max_length=200)),
                ("storage_path", models.CharField(max_length=500)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cases.case",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "case_attachments",
            },
        ),
        migrations.CreateModel(
            name="CaseDocument",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_documents",
                        to="cases.case",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_documents",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "case_documents",
            },
        ),
        migrations.CreateModel(
            name="CaseParticipant",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role_on_case",
                    models.CharField(
                        choices=[
                            ("owner", "owner"),
                            ("coowner", "coowner"),
                            ("watcher", "watcher"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="cases.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "case_participants",
            },
        ),
        migrations.CreateModel(
            name="CaseTask",
            fields=[
                ("task_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("DONE", "DONE"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_tasks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "case_tasks",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("document", "document"),
                            ("case", "case"),
                            ("task", "task"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                ("content", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comments",
            },
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["department"], name="cases_departm_d946e6_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["status"], name="cases_status__1441bd_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["owner"], name="cases_owner_i_1d7d25_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["leader"], name="cases_leader__b8aaf4_idx"),
        ),
        migrations.AddIndex(
            model_name="caseactivitylog",
            index=models.Index(
                fields=["case", "at"], name="case_activi_case_id_d6d1c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseattachment",
            index=models.Index(
                fields=["case", "uploaded_at"], name="case_attach_case_id_d8e101_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casedocument",
            index=models.Index(
                fields=["document", "case"], name="case_docume_documen_c49f83_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="casedocument",
            constraint=models.UniqueConstraint(
                fields=("case", "document"), name="uq_case_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="caseparticipant",
            constraint=models.UniqueConstraint(
                fields=("case", "user"), name="uq_case_user"
            ),
        ),
        migrations.AddIndex(
            model_name="casetask",
            index=models.Index(
                fields=["case", "status"], name="case_tasks_case_id_0e93fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casetask",
            index=models.Index(fields=["due_at"], name="case_tasks_due_at_d8c0f0_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["entity_type", "entity_id", "created_at"],
                name="comments_entity__f74afd_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(("entity_type__in", ("document", "case", "task"))),
                name="chk_comment_entity_type",
            ),
        ),
    ]
