# Generated by Django 5.2.7 on 2025-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_case_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseparticipant",
            name="role_on_case",
            field=models.CharField(
                choices=[
                    ("owner", "owner"),
                    ("coowner", "coowner"),
                    ("assignee", "assignee"),
                    ("watcher", "watcher"),
                ],
                max_length=30,
            ),
        ),
    ]
