# Generated by Django 5.2.7 on 2025-12-02 00:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchiveBackupRecord",
            fields=[
                (
                    "backup_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "method",
                    models.CharField(
                        choices=[("auto", "Tự động"), ("manual", "Thủ công")],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang xử lý"),
                            ("success", "Thành công"),
                            ("failed", "Thất bại"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "archive_backups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveQueueItem",
            fields=[
                (
                    "queue_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=120)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ"),
                            ("processing", "Đang xử lý"),
                            ("completed", "Hoàn thành"),
                            ("failed", "Thất bại"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "archive_queue_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                ("policy_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("retention_years", models.PositiveSmallIntegerField(default=5)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang áp dụng"),
                            ("review", "Cần rà soát"),
                            ("archived", "Đã lưu trữ"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("next_review_at", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "archive_retention_policies",
                "ordering": ["-updated_at"],
            },
        ),
    ]
