# Generated by Django 5.2.7 on 2025-11-06 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('transition_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('doc_in', 'Văn bản đến'), ('doc_out', 'Văn bản đi'), ('case', 'Hồ sơ công việc')], max_length=20)),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('allowed_permissions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_transitions_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_transitions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_transitions',
                'indexes': [models.Index(fields=['module', 'is_active'], name='workflow_tr_module_8c35fa_idx')],
                'constraints': [models.UniqueConstraint(fields=('module', 'from_status', 'to_status'), name='uq_workflow_transition_unique')],
            },
        ),
    ]
