# Generated by Django 5.2.7 on 2025-10-29 20:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("audit_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "CREATE"),
                            ("UPDATE", "UPDATE"),
                            ("DELETE", "DELETE"),
                            ("LOGIN", "LOGIN"),
                            ("EXPORT", "EXPORT"),
                            ("APPROVE", "APPROVE"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("document", "document"),
                            ("case", "case"),
                            ("user", "user"),
                            ("other", "other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("entity_id", models.CharField(blank=True, max_length=64, null=True)),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip", models.CharField(blank=True, max_length=45, null=True)),
                ("before_json", models.JSONField(blank=True, null=True)),
                ("after_json", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "at"],
                        name="audit_logs_entity__5fab27_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("entity_type__in", ("document", "case", "user", "other"))
                        ),
                        name="chk_audit_entity_type",
                    )
                ],
            },
        ),
    ]
